web-server:
  build: .
  ports:
   - 80:3000
  links:
   - data-cache
  command: npm run dev

app-service:
  image: almanac/app-service:dev
  links:
   - data-cache
  restart: always

data-cache:
  image: redis
  volumes_from:
    - cachedb
  command: redis-server --appendonly yes
